name = "activity"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "linkedcaretracker-db"
database_id = "e4401040-c9dd-46c8-be2d-c7295e2d6ea7"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "activity"
